"""initial schema from existing models

Revision ID: 6ebe711cac35
Revises: 
Create Date: 2026-08-18 21:48:45.878950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ebe711cac35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('AdminID', sa.String(length=50), nullable=False),
    sa.Column('AdminPassword', sa.String(length=255), nullable=False),
    sa.Column('AdminName', sa.String(length=255), nullable=False),
    sa.Column('AdminEmail', sa.String(length=255), nullable=False),
    sa.Column('AdminContactNum', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('AdminID')
    )
    op.create_table('guest_user',
    sa.Column('GuestID', sa.String(length=50), nullable=False),
    sa.Column('TokenHash', sa.String(length=64), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('ExpiresAt', sa.DateTime(), nullable=False),
    sa.Column('Status', sa.Enum('pending', 'enrolling', 'ready', 'expired', name='guest_user_status'), nullable=False),
    sa.Column('LastRecognizedAt', sa.DateTime(), nullable=True),
    sa.Column('LastRecognitionResult', sa.Boolean(), nullable=True),
    sa.Column('LastRecognitionConfidence', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('GuestID')
    )
    op.create_table('staff',
    sa.Column('StaffID', sa.String(length=50), nullable=False),
    sa.Column('StaffPassword', sa.String(length=255), nullable=False),
    sa.Column('StaffName', sa.String(length=255), nullable=False),
    sa.Column('StaffEmail', sa.String(length=255), nullable=False),
    sa.Column('StaffContactNum', sa.String(length=20), nullable=False),
    sa.Column('AccountStatus', sa.Enum('Pending', 'Approved', 'Rejected', name='account_status'), nullable=False),
    sa.PrimaryKeyConstraint('StaffID')
    )
    op.create_table('student',
    sa.Column('StudID', sa.String(length=50), nullable=False),
    sa.Column('StudPassword', sa.String(length=255), nullable=False),
    sa.Column('StudName', sa.String(length=255), nullable=False),
    sa.Column('StudEmail', sa.String(length=255), nullable=False),
    sa.Column('StudContactNum', sa.String(length=20), nullable=False),
    sa.Column('AccountStatus', sa.Enum('Pending', 'Approved', 'Rejected', name='account_status'), nullable=False),
    sa.PrimaryKeyConstraint('StudID')
    )
    op.create_table('announcement',
    sa.Column('AnnounceID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('AdminID', sa.String(length=50), nullable=False),
    sa.Column('PostDate', sa.DateTime(), nullable=False),
    sa.Column('Title', sa.String(length=255), nullable=False),
    sa.Column('Content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['AdminID'], ['admin.AdminID'], ),
    sa.PrimaryKeyConstraint('AnnounceID')
    )
    op.create_table('feedback',
    sa.Column('FeedbackID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('StudID', sa.String(length=50), nullable=True),
    sa.Column('StaffID', sa.String(length=50), nullable=True),
    sa.Column('Subject', sa.String(length=255), nullable=False),
    sa.Column('Content', sa.Text(), nullable=False),
    sa.Column('PostDate', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['StaffID'], ['staff.StaffID'], ),
    sa.ForeignKeyConstraint(['StudID'], ['student.StudID'], ),
    sa.PrimaryKeyConstraint('FeedbackID')
    )
    op.create_table('registeredfaces',
    sa.Column('FaceID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('FaceIMG', sa.Text(), nullable=False),
    sa.Column('EmbeddingsJSON', sa.Text(), nullable=True),
    sa.Column('StudID', sa.String(length=50), nullable=True),
    sa.Column('StaffID', sa.String(length=50), nullable=True),
    sa.Column('GuestID', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['GuestID'], ['guest_user.GuestID'], ),
    sa.ForeignKeyConstraint(['StaffID'], ['staff.StaffID'], ),
    sa.ForeignKeyConstraint(['StudID'], ['student.StudID'], ),
    sa.PrimaryKeyConstraint('FaceID')
    )
    op.create_table('report',
    sa.Column('ReportID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('StudID', sa.String(length=50), nullable=True),
    sa.Column('StaffID', sa.String(length=50), nullable=True),
    sa.Column('Subject', sa.String(length=255), nullable=False),
    sa.Column('Content', sa.Text(), nullable=False),
    sa.Column('PostDate', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['StaffID'], ['staff.StaffID'], ),
    sa.ForeignKeyConstraint(['StudID'], ['student.StudID'], ),
    sa.PrimaryKeyConstraint('ReportID')
    )
    op.create_table('roomlist',
    sa.Column('RoomID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('AdminID', sa.String(length=50), nullable=True),
    sa.Column('RoomName', sa.String(length=255), nullable=False),
    sa.Column('roomIMG', sa.String(length=500), nullable=True),
    sa.Column('RoomInfo', sa.Text(), nullable=True),
    sa.Column('RoomType', sa.String(length=100), nullable=True),
    sa.Column('RoomStatus', sa.Enum('Available', 'Occupied', 'Maintenance', name='room_status'), nullable=False),
    sa.ForeignKeyConstraint(['AdminID'], ['admin.AdminID'], ),
    sa.PrimaryKeyConstraint('RoomID'),
    sa.UniqueConstraint('RoomName')
    )
    op.create_table('eventbookings',
    sa.Column('EBookID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('RoomID', sa.Integer(), nullable=False),
    sa.Column('StudID', sa.String(length=50), nullable=True),
    sa.Column('StaffID', sa.String(length=50), nullable=True),
    sa.Column('Start', sa.DateTime(), nullable=False),
    sa.Column('End', sa.DateTime(), nullable=False),
    sa.Column('Purpose', sa.Text(), nullable=False),
    sa.Column('AddDetail', sa.Text(), nullable=True),
    sa.Column('EbookStatus', sa.Enum('Upcoming', 'Ongoing', 'Completed', 'Cancelled', name='booking_status'), nullable=False),
    sa.Column('CheckInMethod', sa.String(length=50), nullable=False),
    sa.Column('qr_token_hash', sa.String(length=128), nullable=True),
    sa.Column('qr_token_issued_at', sa.DateTime(), nullable=True),
    sa.Column('qr_token_redeemed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['RoomID'], ['roomlist.RoomID'], ),
    sa.ForeignKeyConstraint(['StaffID'], ['staff.StaffID'], ),
    sa.ForeignKeyConstraint(['StudID'], ['student.StudID'], ),
    sa.PrimaryKeyConstraint('EBookID')
    )
    op.create_table('roomaccesslog',
    sa.Column('rmaID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('RoomID', sa.Integer(), nullable=False),
    sa.Column('StudID', sa.String(length=50), nullable=True),
    sa.Column('StaffID', sa.String(length=50), nullable=True),
    sa.Column('Status', sa.Integer(), nullable=False),
    sa.Column('Timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['RoomID'], ['roomlist.RoomID'], ),
    sa.ForeignKeyConstraint(['StaffID'], ['staff.StaffID'], ),
    sa.ForeignKeyConstraint(['StudID'], ['student.StudID'], ),
    sa.PrimaryKeyConstraint('rmaID')
    )
    op.create_table('roombookings',
    sa.Column('RBookID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('RoomID', sa.Integer(), nullable=False),
    sa.Column('StudID', sa.String(length=50), nullable=True),
    sa.Column('StaffID', sa.String(length=50), nullable=True),
    sa.Column('Start', sa.DateTime(), nullable=False),
    sa.Column('End', sa.DateTime(), nullable=False),
    sa.Column('Purpose', sa.Text(), nullable=False),
    sa.Column('RBookStatus', sa.Enum('Upcoming', 'Ongoing', 'Completed', 'Cancelled', name='booking_status'), nullable=False),
    sa.Column('CheckInMethod', sa.String(length=50), nullable=False),
    sa.Column('qr_token_hash', sa.String(length=128), nullable=True),
    sa.Column('qr_token_issued_at', sa.DateTime(), nullable=True),
    sa.Column('qr_token_redeemed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['RoomID'], ['roomlist.RoomID'], ),
    sa.ForeignKeyConstraint(['StaffID'], ['staff.StaffID'], ),
    sa.ForeignKeyConstraint(['StudID'], ['student.StudID'], ),
    sa.PrimaryKeyConstraint('RBookID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roombookings')
    op.drop_table('roomaccesslog')
    op.drop_table('eventbookings')
    op.drop_table('roomlist')
    op.drop_table('report')
    op.drop_table('registeredfaces')
    op.drop_table('feedback')
    op.drop_table('announcement')
    op.drop_table('student')
    op.drop_table('staff')
    op.drop_table('guest_user')
    op.drop_table('admin')
    # ### end Alembic commands ###
